export type SubCategory = {
  titel: string;
  synonymer: string[];
};

export type FoodCategory = {
  id: string;
  kategori: string;
  isCommon: boolean;
  undertyper: SubCategory[];
};

const foodData: FoodCategory[] = [
  {
    id: "sugar",
    kategori: "Sukker",
    isCommon: true,
    undertyper: [
      {
        titel: "Sukkerarter",
        synonymer: [
          "Dextrose",
          "Druesukker",
          "Frugtsukker",
          "Fruktose",
          "Galaktose",
          "Glukose",
          "Laktose",
          "Maltose",
          "Maltsukker",
          "Sakkarose",
          "Sucrose",
          "Tagatose",
        ],
      },
      {
        titel: "Flydende",
        synonymer: [
          "Agavesirup",
          "Ahornsirup",
          "Bygmaltsirup",
          "Daddelsirup",
          "Fruktosesirup",
          "Glukose-fruktosesirup",
          "Glukosesirup",
          "HFCS",
          "High Fructose Corn Syrup",
          "Honning",
          "Invertsukkersirup",
          "Lys sirup",
          "Lønsirup",
          "Majssirup",
          "Mørk sirup",
          "Rismaltsirup",
          "Rissirup",
          "Sukkerrørssaft",
        ],
      },
      {
        titel: "Faste former",
        synonymer: [
          "Brun farin",
          "Brunt sukker",
          "Bygmalt",
          "Cassonade",
          "Demerara",
          "Dextrin",
          "Flormelis",
          "Invertsukker",
          "Isomaltulose",
          "Jaggery",
          "Kandis",
          "Karamel",
          "Kokosblomstsukker",
          "Kokossukker",
          "Maltekstrakt",
          "Maltodextrin",
          "Melasse",
          "Muscovado",
          "Palmesukker",
          "Panela",
          "Perlesukker",
          "Raffinade",
          "Rørsukker",
          "Treacle",
          "Turbinado",
        ],
      },
    ],
  },
  {
    id: "sweeteners",
    kategori: "Sødemidler",
    isCommon: false,
    undertyper: [
      {
        titel: "Sukkeralkoholer",
        synonymer: [
          "Erythritol (E968)",
          "Isomalt (E953)",
          "Lactitol (E966)",
          "Maltitol (E965)",
          "Mannitol (E421)",
          "Sorbitol (E420)",
          "Xylitol (E967)",
        ],
      },
      {
        titel: "Sødestoffer",
        synonymer: [
          "Acesulfam-K (E950)",
          "Advantam (E969)",
          "Alitame (E956)",
          "Aspartam (E951)",
          "Cyclamat (E952)",
          "Neohesperidin DC (E959)",
          "Neotam (E961)",
          "Saccharin (E954)",
          "Stevia (E960)",
          "Sukralose (E955)",
          "Taumatin (E957)",
        ],
      },
    ],
  },
  {
    id: "animal",
    kategori: "Animalsk",
    isCommon: true,
    undertyper: [
      {
        titel: "Kød og fjerkræ",
        synonymer: [
          "Bouillon",
          "Fjerkræ",
          "Kødekstrakt",
          "Lard",
          "Smult",
          "Talg",
          "Vildt",
        ],
      },
      {
        titel: "Fisk og skaldyr",
        synonymer: [
          "Ansjoser",
          "Fiskelim",
          "Fiskeolie",
          "Isinglass",
          "Skaldyr",
        ],
      },
      {
        titel: "Skjulte kilder",
        synonymer: [
          "Adeps",
          "Albumin",
          "Ambergris",
          "Bivoks (E901)",
          "Carmine (E120)",
          "Chitosan",
          "D3-vitamin",
          "Gelatine",
          "Glycerol (E422)",
          "Husblas",
          "Kastoreum",
          "Lanolin",
          "Lysozym (E1105)",
          "Mælkesyre (E270)",
          "Osteløbe",
          "Pepsin",
          "Shellak (E904)",
        ],
      },
    ],
  },
  {
    id: "gluten",
    kategori: "Gluten og Hvede",
    isCommon: true,
    undertyper: [
      {
        titel: "Kornsorter",
        synonymer: [
          "Byg",
          "Dinkel",
          "Durum",
          "Einkorn",
          "Emmer",
          "Enkorn",
          "Hvede",
          "Kamut",
          "Rug",
          "Spelt",
          "Triticale",
        ],
      },
      {
        titel: "Mel og produkter",
        synonymer: [
          "Atta",
          "Bulgur",
          "Couscous",
          "Fuldkornshvede",
          "Grahamsmel",
          "Hvedeklid",
          "Hvedekim",
          "Hvedeprotein",
          "Hvedestivelse",
          "Panko",
          "Rasp",
          "Seitan",
          "Semolina",
          "Sigtemel",
        ],
      },
      {
        titel: "Skjult gluten",
        synonymer: [
          "Bygmalt",
          "Malt",
          "Malteddike",
          "Maltekstrakt",
          "Urtemalt",
        ],
      },
    ],
  },
  {
    id: "dairy",
    kategori: "Mejeri og Laktose",
    isCommon: true,
    undertyper: [
      {
        titel: "Mælkeprodukter",
        synonymer: [
          "Creme fraiche",
          "Fløde",
          "Kærnemælk",
          "Ost",
          "Skyr",
          "Smør",
          "Yoghurt",
        ],
      },
      {
        titel: "Bestanddele",
        synonymer: [
          "Ghee",
          "Isolat",
          "Kasein",
          "Kaseinat",
          "Kondenseret mælk",
          "Laktalbumin",
          "Laktoglobulun",
          "Laktose",
          "Mælkefedt",
          "Mælkeprotein",
          "Mælkepulver",
          "Mælkesukker",
          "Myseost",
          "Recaldent",
          "Valle",
          "Vallepermeat",
          "Valleprotein",
          "Vallepulver",
        ],
      },
    ],
  },
  {
    id: "nuts",
    kategori: "Nødder og Peanuts",
    isCommon: false,
    undertyper: [
      {
        titel: "Trænødder",
        synonymer: [
          "Cashewnødder",
          "Hasselnødder",
          "Kastanjer",
          "Macadamianødder",
          "Mandler",
          "Paranødder",
          "Pekannødder",
          "Pinjekerner",
          "Pistacienødder",
          "Valnødder",
        ],
      },
      {
        titel: "Jordnødder",
        synonymer: [
          "Jordnøddeolie",
          "Jordnødder",
          "Mandelmel",
          "Marcipan",
          "Nougat",
          "Peanuts",
        ],
      },
    ],
  },
  {
    id: "soy",
    kategori: "Soja",
    isCommon: false,
    undertyper: [
      {
        titel: "Produkter",
        synonymer: [
          "Edamame",
          "Miso",
          "Natto",
          "Okara",
          "Sojamælk",
          "Sojaprotein",
          "Sojasauce",
          "Tamari",
          "Tempeh",
          "Tofu",
          "Yuba",
        ],
      },
      {
        titel: "Skjult soja",
        synonymer: [
          "E322",
          "Glycine max",
          "Kinnoko",
          "Sojalecithin",
          "Sojamel",
        ],
      },
    ],
  },
  {
    id: "egg",
    kategori: "Æg",
    isCommon: false,
    undertyper: [
      {
        titel: "Bestanddele",
        synonymer: ["Æggeblomme", "Æggehvide", "Æggehvidepulver", "Æggepulver"],
      },
      {
        titel: "Skjulte kilder",
        synonymer: [
          "Albumin",
          "Avidin",
          "Conalbumin",
          "Globulin",
          "Lecithin (E322)",
          "Livetin",
          "Lysozym (E1105)",
          "Majonæse",
          "Ovalbumin",
          "Ovomucoid",
          "Ovomucin",
          "Ovovitellin",
        ],
      },
    ],
  },
];

export default foodData;
