// export const DIET_MAP: Record<string, string[]> = {
//   keto: ["sukker", "hvede", "kartofler", "ris", "pasta", "majs"],
//   vegansk: [
//     "kød",
//     "mælk",
//     "æg",
//     "honning",
//     "gelatine",
//     "valle",
//     "smør",
//     "kasein",
//     "karmin",
//     "e120",
//     "bivoks",
//     "e901",
//     "shellak",
//     "e904",
//   ],
//   pæleo: [
//     "sukker",
//     "mejeriprodukter",
//     "korn",
//     "bælgfrugter",
//     "kunstige sødestoffer",
//     "solsikkeolie",
//     "majsolie",
//     "sojaolie",
//   ],
//   vegetarisk: [
//     "kød",
//     "fisk",
//     "skaldyr",
//     "fjerkræ",
//     "gelatine",
//     "karmin",
//     "e120",
//   ],
// };

// export const HEALTH_MAP: Record<string, string[]> = {
//   "Anti-inflammatorisk": [
//     "sukker",
//     "hvede",
//     "solsikkeolie",
//     "majsolie",
//     "sojaolie",
//     "tidselolie",
//     "friture",
//     "margarine",
//     "svinefedt",
//     "forarbejdet kød",
//     "pølser",
//     "bacon",
//     "aspartam",
//     "e951",
//   ],
//   Diabetes: [
//     "sukker",
//     "rørsukker",
//     "hvidt sukker",
//     "brunt sukker",
//     "flormelis",
//     "glukose",
//     "glukosesirup",
//     "fruktose",
//     "fruktosesirup",
//     "dextrose",
//     "sirup",
//     "ahornsirup",
//     "agavesirup",
//     "honning",
//     "maltodextrin",
//     "maltose",
//     "invertsukker",
//     "karamel",
//     "melasse",
//     "druesukker",
//     "majssirup",
//     "isomaltulose",
//     "trehalose",
//     "palmesukker",
//     "kokossukker",
//     "rissirup",
//     "daddelsirup",
//     "roesukker",
//     "perlesukker",
//     "kandis",
//   ],
//   "Forhøjet blodtryk": [
//     "lakridsrod",
//     "salmiak",
//     "ammoniumklorid",
//     "e510",
//     "lakridsekstrakt",
//     "glycyrrhizin",
//     "lakridspulver",
//     "mononatriumglutamat",
//     "e621",
//     "smagsforstærker",
//     "sojasovs",
//     "bouillon",
//     "kødekstrakt",
//     "gærekstrakt",
//   ],
//   "Forhøjet kolesterol": [
//     "palmeolie",
//     "palmefedt",
//     "kokosolie",
//     "kokosfedt",
//     "smør",
//     "fløde",
//     "svinefedt",
//     "oksefedt",
//     "lammefedt",
//     "hærdet fedt",
//     "hærdet vegetabilsk fedt",
//     "delvist hærdet fedt",
//     "transfedt",
//     "transfedtsyrer",
//     "hydrogeneret fedt",
//     "hydrogeneret olie",
//     "kakaosmør",
//     "ghee",
//     "piskefløde",
//     "creme fraiche",
//     "spæk",
//     "tælle",
//   ],
//   Gravid: [
//     "alkohol",
//     "ethanol",
//     "råmælk",
//     "upasteuriseret mælk",
//     "upasteuriseret ost",
//     "rå ost",
//     "skimmelost",
//     "roquefort",
//     "brie",
//     "camembert",
//     "gorgonzola",
//     "råt kød",
//     "spegepølse",
//     "parmaskinke",
//     "salami",
//     "rå fisk",
//     "gravad laks",
//     "koldrøget laks",
//     "lakridsrod",
//     "ginseng",
//     "koffein",
//     "guarana",
//     "taurin",
//     "aloe vera",
//     "tun",
//     "helletun",
//     "sværdfisk",
//     "rokkefisk",
//     "gedde",
//     "aborre",
//   ],
//   "Histamin-intolerance": [
//     "tomat",
//     "spinat",
//     "aubergine",
//     "avocado",
//     "rødvin",
//     "hvidvin",
//     "øl",
//     "fermenteret",
//     "gær",
//     "sojasovs",
//     "miso",
//     "tempeh",
//     "spegepølse",
//     "bacon",
//     "salami",
//     "parmesan",
//     "cheddar",
//     "gouda",
//     "roquefort",
//     "eddike",
//     "sennep",
//     "ketchup",
//     "surkål",
//     "kombucha",
//   ],
//   "Irritabel tyktarm": [
//     "løg",
//     "hvidløg",
//     "løgpulver",
//     "hvidløgspulver",
//     "porre",
//     "forårsløg",
//     "sjalotteløg",
//     "hvede",
//     "rug",
//     "byg",
//     "inulin",
//     "cikorie",
//     "cikorierod",
//     "æble",
//     "pære",
//     "vandmelon",
//     "fersken",
//     "blomme",
//     "abrikos",
//     "kirsebær",
//     "brombær",
//     "blomkål",
//     "svampe",
//     "ærter",
//     "bønner",
//     "linser",
//     "kikærter",
//     "sojabønner",
//     "laktose",
//     "agavesirup",
//     "sorbitol",
//     "mannitol",
//     "xylitol",
//     "maltitol",
//     "isomalt",
//     "e420",
//     "e421",
//     "e953",
//     "e965",
//     "e966",
//     "e967",
//     "mælk",
//     "yoghurt",
//     "hytteost",
//   ],
//   Migræne: [
//     "e621",
//     "mononatriumglutamat",
//     "aspartam",
//     "e951",
//     "sucralose",
//     "e955",
//     "nitrat",
//     "nitrit",
//     "e249",
//     "e250",
//     "e251",
//     "e252",
//     "tyramin",
//     "chokolade",
//     "kakao",
//     "rødvin",
//     "lagret ost",
//     "citrusekstrakt",
//   ],
// };

// export const ALLERGY_MAP: Record<string, string[]> = {
//   Nødder: [
//     "nødder",
//     "mandler",
//     "hasselnødder",
//     "valnødder",
//     "cashewnødder",
//     "pekannødder",
//     "paranødder",
//     "pistacienødder",
//     "macadamianødder",
//   ],
//   Laktose: [
//     "mælk",
//     "laktose",
//     "valle",
//     "fløde",
//     "smør",
//     "ost",
//     "kasein",
//     "skummetmælkspulver",
//   ],
//   Gluten: ["gluten", "hvede", "rug", "byg", "havre", "spelt", "durum"],
//   Æg: ["æg", "æggehvide", "æggeblomme", "æggepulver", "albumin"],
//   Skalddyr: [
//     "skaldyr",
//     "rejer",
//     "krabbe",
//     "hummer",
//     "krebs",
//     "muslinger",
//     "østers",
//   ],
//   Soja: ["soja", "sojabønner", "sojalecitin", "tofu", "edamame"],
//   Fisk: ["fisk", "tun", "laks", "torsk", "sild", "fiskeolie"],
//   Sukker: [
//     "sukker",
//     "rørsukker",
//     "roesukker",
//     "sakkarose",
//     "flormelis",
//     "brun farin",
//     "perlesukker",
//     "kandis",
//     "melasse",
//     "karamel",
//     "sirup",
//     "glukosesirup",
//     "maltsirup",
//     "rissirup",
//     "daddelsirup",
//     "ahornsirup",
//     "majssirup",
//     "maltodextrin",
//     "glukose",
//     "dextrose",
//     "maltose",
//     "invertsukker",
//     "isomaltulose",
//     "trehalose",
//     "honning",
//     "palmesukker",
//     "kokossukker",
//     "druesukker",
//     "maltekstrakt",
//   ],
//   Alkohol: [
//     "alkohol",
//     "ethanol",
//     "ethylalkohol",
//     "vin",
//     "rødvin",
//     "hvidvin",
//     "øl",
//     "spiritus",
//     "snaps",
//     "rom",
//     "vodka",
//     "gin",
//     "whisky",
//     "likør",
//     "cognac",
//     "brandy",
//     "sherry",
//     "portvin",
//     "vineddike",
//     "hvidvinseddike",
//     "rødvinseddike",
//     "romaroma",
//     "snapsaroma",
//     "cider",
//     "frugtvin",
//     "sake",
//     "soju",
//     "brændevin",
//     "e1519",
//     "benzylalkohol",
//   ],
// };

// export const DIET_OPTIONS = Object.keys(DIET_MAP);
// export const HEALTH_OPTIONS = Object.keys(HEALTH_MAP);
// export const ALLERGY_OPTIONS = Object.keys(ALLERGY_MAP);

export const DIET_MAP: Record<string, string[]> = {
  keto: ["sukker", "hvede", "kartofler", "ris", "pasta", "majs"],
  vegan: [
    "kød",
    "mælk",
    "æg",
    "honning",
    "gelatine",
    "valle",
    "smør",
    "kasein",
    "karmin",
    "e120",
    "bivoks",
    "e901",
    "shellak",
    "e904",
  ],
  paleo: [
    "sukker",
    "mejeriprodukter",
    "korn",
    "bælgfrugter",
    "kunstige sødestoffer",
    "solsikkeolie",
    "majsolie",
    "sojaolie",
  ],
  vegetarian: [
    "kød",
    "fisk",
    "skaldyr",
    "fjerkræ",
    "gelatine",
    "karmin",
    "e120",
  ],
};

export const HEALTH_MAP: Record<string, string[]> = {
  anti_inflammatory: [
    "sukker",
    "hvede",
    "solsikkeolie",
    "majsolie",
    "sojaolie",
    "tidselolie",
    "friture",
    "margarine",
    "svinefedt",
    "forarbejdet kød",
    "pølser",
    "bacon",
    "aspartam",
    "e951",
  ],
  diabetes: [
    "sukker",
    "rørsukker",
    "hvidt sukker",
    "brunt sukker",
    "flormelis",
    "glukose",
    "glukosesirup",
    "fruktose",
    "fruktosesirup",
    "dextrose",
    "sirup",
    "ahornsirup",
    "agavesirup",
    "honning",
    "maltodextrin",
    "maltose",
    "invertsukker",
    "karamel",
    "melasse",
    "druesukker",
    "majssirup",
    "isomaltulose",
    "trehalose",
    "palmesukker",
    "kokossukker",
    "rissirup",
    "daddelsirup",
    "roesukker",
    "perlesukker",
    "kandis",
  ],
  high_blood_pressure: [
    "lakridsrod",
    "salmiak",
    "ammoniumklorid",
    "e510",
    "lakridsekstrakt",
    "glycyrrhizin",
    "lakridspulver",
    "mononatriumglutamat",
    "e621",
    "smagsforstærker",
    "sojasovs",
    "bouillon",
    "kødekstrakt",
    "gærekstrakt",
  ],
  high_cholesterol: [
    "palmeolie",
    "palmefedt",
    "kokosolie",
    "kokosfedt",
    "smør",
    "fløde",
    "svinefedt",
    "oksefedt",
    "lammefedt",
    "hærdet fedt",
    "hærdet vegetabilsk fedt",
    "delvist hærdet fedt",
    "transfedt",
    "transfedtsyrer",
    "hydrogeneret fedt",
    "hydrogeneret olie",
    "kakaosmør",
    "ghee",
    "piskefløde",
    "creme fraiche",
    "spæk",
    "tælle",
  ],
  pregnant: [
    "alkohol",
    "ethanol",
    "råmælk",
    "upasteuriseret mælk",
    "upasteuriseret ost",
    "rå ost",
    "skimmelost",
    "roquefort",
    "brie",
    "camembert",
    "gorgonzola",
    "råt kød",
    "spegepølse",
    "parmaskinke",
    "salami",
    "rå fisk",
    "gravad laks",
    "koldrøget laks",
    "lakridsrod",
    "ginseng",
    "koffein",
    "guarana",
    "taurin",
    "aloe vera",
    "tun",
    "helletun",
    "sværdfisk",
    "rokkefisk",
    "gedde",
    "aborre",
  ],
  histamine: [
    "tomat",
    "spinat",
    "aubergine",
    "avocado",
    "rødvin",
    "hvidvin",
    "øl",
    "fermenteret",
    "gær",
    "sojasovs",
    "miso",
    "tempeh",
    "spegepølse",
    "bacon",
    "salami",
    "parmesan",
    "cheddar",
    "gouda",
    "roquefort",
    "eddike",
    "sennep",
    "ketchup",
    "surkål",
    "kombucha",
  ],
  ibs: [
    "løg",
    "hvidløg",
    "løgpulver",
    "hvidløgspulver",
    "porre",
    "forårsløg",
    "sjalotteløg",
    "hvede",
    "rug",
    "byg",
    "inulin",
    "cikorie",
    "cikorierod",
    "æble",
    "pære",
    "vandmelon",
    "fersken",
    "blomme",
    "abrikos",
    "kirsebær",
    "brombær",
    "blomkål",
    "svampe",
    "ærter",
    "bønner",
    "linser",
    "kikærter",
    "sojabønner",
    "laktose",
    "agavesirup",
    "sorbitol",
    "mannitol",
    "xylitol",
    "maltitol",
    "isomalt",
    "e420",
    "e421",
    "e953",
    "e965",
    "e966",
    "e967",
    "mælk",
    "yoghurt",
    "hytteost",
  ],
  migraine: [
    "e621",
    "mononatriumglutamat",
    "aspartam",
    "e951",
    "sucralose",
    "e955",
    "nitrat",
    "nitrit",
    "e249",
    "e250",
    "e251",
    "e252",
    "tyramin",
    "chokolade",
    "kakao",
    "rødvin",
    "lagret ost",
    "citrusekstrakt",
  ],
};

export const ALLERGY_MAP: Record<string, string[]> = {
  nuts: [
    "nødder",
    "mandler",
    "hasselnødder",
    "valnødder",
    "cashewnødder",
    "pekannødder",
    "paranødder",
    "pistacienødder",
    "macadamianødder",
  ],
  lactose: [
    "mælk",
    "laktose",
    "valle",
    "fløde",
    "smør",
    "ost",
    "kasein",
    "skummetmælkspulver",
  ],
  gluten: ["gluten", "hvede", "rug", "byg", "havre", "spelt", "durum"],
  eggs: ["æg", "æggehvide", "æggeblomme", "æggepulver", "albumin"],
  shellfish: [
    "skaldyr",
    "rejer",
    "krabbe",
    "hummer",
    "krebs",
    "muslinger",
    "østers",
  ],
  soy: ["soja", "sojabønner", "sojalecitin", "tofu", "edamame"],
  fish: ["fisk", "tun", "laks", "torsk", "sild", "fiskeolie"],
  sugar: [
    "sukker",
    "rørsukker",
    "roesukker",
    "sakkarose",
    "flormelis",
    "brun farin",
    "perlesukker",
    "kandis",
    "melasse",
    "karamel",
    "sirup",
    "glukosesirup",
    "maltsirup",
    "rissirup",
    "daddelsirup",
    "ahornsirup",
    "majssirup",
    "maltodextrin",
    "glukose",
    "dextrose",
    "maltose",
    "invertsukker",
    "isomaltulose",
    "trehalose",
    "honning",
    "palmesukker",
    "kokossukker",
    "druesukker",
    "maltekstrakt",
  ],
  alcohol: [
    "alkohol",
    "ethanol",
    "ethylalkohol",
    "vin",
    "rødvin",
    "hvidvin",
    "øl",
    "spiritus",
    "snaps",
    "rom",
    "vodka",
    "gin",
    "whisky",
    "likør",
    "cognac",
    "brandy",
    "sherry",
    "portvin",
    "vineddike",
    "hvidvinseddike",
    "rødvinseddike",
    "romaroma",
    "snapsaroma",
    "cider",
    "frugtvin",
    "sake",
    "soju",
    "brændevin",
    "e1519",
    "benzylalkohol",
  ],
};

export const DIET_OPTIONS = Object.keys(DIET_MAP);
export const HEALTH_OPTIONS = Object.keys(HEALTH_MAP);
export const ALLERGY_OPTIONS = Object.keys(ALLERGY_MAP);
